# Generated by Django 2.2.3 on 2020-01-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('prenom', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('fonction', models.CharField(blank=True, max_length=128, null=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('evaluation', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
