# Generated by Django 2.2.3 on 2020-01-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=128)),
                ('type_bien', models.CharField(max_length=128)),
                ('superfecie_min', models.IntegerField()),
                ('superfecie_max', models.IntegerField()),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projets.Projet')),
            ],
        ),
        migrations.CreateModel(
            name='SubOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_metre', models.FloatField()),
                ('prix_min', models.FloatField()),
                ('existence_de_noire', models.BooleanField(default=False)),
                ('noir_montant', models.IntegerField()),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres.Offre')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_metre', models.FloatField()),
                ('prix_min', models.FloatField()),
                ('prix_max', models.FloatField()),
                ('existence_noire', models.BooleanField()),
                ('montant_noire', models.FloatField()),
                ('pourcentage_noire', models.FloatField()),
                ('nombre_piece', models.IntegerField()),
                ('etage', models.IntegerField()),
                ('elevation_immeuble', models.IntegerField()),
                ('vis_a_vis', models.CharField(max_length=255)),
                ('nombre_facade', models.IntegerField()),
                ('utilisation_RDC', models.CharField(choices=[('habitaion', 'Habitaion'), ('commercial', 'Commercial')], max_length=128)),
                ('id_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres.Offre')),
            ],
        ),
        migrations.CreateModel(
            name='ModalitePaiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versement_1', models.IntegerField()),
                ('pourcentage_versement1', models.IntegerField()),
                ('versement_2', models.IntegerField()),
                ('pourcentage_versement2', models.IntegerField()),
                ('versement_3', models.IntegerField()),
                ('pourcentage_versement3', models.IntegerField()),
                ('versement_4', models.IntegerField()),
                ('pourcentage_versement4', models.IntegerField()),
                ('nombre_piece', models.IntegerField()),
                ('etage', models.IntegerField()),
                ('elevation_immeuble', models.IntegerField()),
                ('vis_a_vis', models.CharField(max_length=255)),
                ('nombre_facade', models.IntegerField()),
                ('utilisation_RDC', models.CharField(choices=[('habitaion', 'Habitaion'), ('commercial', 'Commercial')], max_length=128)),
                ('id_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offres.Offre')),
            ],
        ),
    ]
