# Generated by Django 2.2.3 on 2020-01-28 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Categorie'),
        ),
    ]
