# Generated by Django 2.2.3 on 2020-01-29 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200129_0006'),
        ('offres', '0002_auto_20200128_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type_bien', models.CharField(max_length=64)),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Categorie')),
            ],
        ),
        migrations.AlterField(
            model_name='offre',
            name='type_bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offres.TypeBien'),
        ),
    ]
