# Generated by Django 2.2.3 on 2020-01-28 00:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promoteurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoteur',
            name='user',
        ),
        migrations.AddField(
            model_name='promoteur',
            name='nom',
            field=models.CharField(default=datetime.datetime(2020, 1, 28, 0, 6, 52, 669815, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promoteur',
            name='prenom',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
