# Generated by Django 2.2.3 on 2020-01-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_promoteur',
            field=models.BooleanField(default=False),
        ),
    ]
