# Generated by Django 2.2.3 on 2020-01-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='date_enregistrement',
            new_name='timestamp',
        ),
    ]
