# Generated by Django 2.2.3 on 2020-01-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promoteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=64)),
                ('site_web', models.CharField(max_length=255)),
                ('adresse_siege_social', models.TextField(max_length=128)),
                ('promoteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='promoteurs.Promoteur')),
            ],
        ),
    ]
