# Generated by Django 2.2.3 on 2020-01-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promoteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('region1', models.CharField(max_length=128)),
                ('region2', models.CharField(max_length=128)),
                ('region3', models.CharField(max_length=128)),
                ('superficie', models.IntegerField()),
                ('consistance', models.CharField(max_length=128)),
                ('annee_lancement', models.TimeField()),
                ('nom_promoteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promoteurs.Promoteur')),
            ],
        ),
    ]
