# Generated by Django 2.2.3 on 2020-01-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marques', '0001_initial'),
        ('promoteurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=128)),
                ('image_logo', models.ImageField(upload_to='projects/%Y/%m/%d')),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('region1', models.CharField(blank=True, max_length=128, null=True)),
                ('region2', models.CharField(blank=True, max_length=128, null=True)),
                ('region3', models.CharField(blank=True, max_length=128, null=True)),
                ('superficie', models.IntegerField()),
                ('localisation', models.CharField(blank=True, max_length=128, null=True)),
                ('consistance', models.IntegerField()),
                ('annee_lancement', models.DateTimeField()),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marques.Marque')),
                ('nom_promoteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promoteurs.Promoteur')),
            ],
        ),
    ]
